from Advanced_DataStructures import *

# st=stack_LinkedList()
# st.push(1)
# st.push(101)
# st.push(10)
# st.push(111)
# st.push(166)
# st.push(144)
# print(st.length())
# print(st.pop())
# print(st.pop())
# print(st.peek())
# print(st.length())

q=Queue()

q.enqueue(10)
q.enqueue(40)
q.enqueue(70)
q.enqueue(89)
print(q.length())
print(q.dequeue())
print(q.length())
print(q.peek_first())
print(q.peek_last())
